"""add host and port to stream unit

Revision ID: e9721d811a25
Revises: b01217c92f96
Create Date: 2023-11-11 17:00:55.155649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9721d811a25'
down_revision: Union[str, None] = 'b01217c92f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_units', sa.Column('host', sa.String(), nullable=True))
    op.add_column('stream_units', sa.Column('port', sa.Integer(), nullable=True))
    op.alter_column('stream_units', 'api_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('stream_unit_video_uri_uniq', 'stream_units', type_='unique')
    op.create_unique_constraint('stream_unit_host_port_uniq', 'stream_units', ['host', 'port'])
    op.drop_column('stream_units', 'video_url')


def downgrade() -> None:
    op.add_column('stream_units', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('stream_unit_host_port_uniq', 'stream_units', type_='unique')
    op.create_unique_constraint('stream_unit_video_uri_uniq', 'stream_units', ['video_url'])
    op.alter_column('stream_units', 'api_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('stream_units', 'port')
    op.drop_column('stream_units', 'host')