import cv2
from flask import Flask, Response

app = Flask(__name__)

# Open the USB camera
camera = cv2.VideoCapture(-1)


def generate_frames():
    while True:
        # Read the current frame from the camera
        success, frame = camera.read()
        if not success:
            break
        else:
            # Encode the frame in JPEG format
            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()

        # Yield the frame in byte format
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@app.route('/video_feed')
def video_feed():
    # Return the response generated by the generate_frames() function as a video feed
    return Response(generate_frames(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


if __name__ == '__main__':
    # Run the Flask app on the specified IP address and port
    app.run(host='0.0.0.0', port=5000)

